Enable using AccessMessage outside of the crate
drogue-iot/drogue-device pull request #287
Opened 2022-05-31 14:59 UTC by dejanb

As ElementHandlers are using AccessMessage and I want to use the same abstractions in bluer, there has to be a way to create an AccessMessage outside of crate. I additionally marked some of the fields as optional as they are not used in this context. I'm still not sure if that's the right way to go (or should we maybe redesign the structs). Here's the example of how this is used

https://github.com/dejanb/bluer/blob/mesh/bluer/src/mesh/mod.rs#L74

Let me know if you have any thoughts on how to better implement this.

2022-05-31 15:06 UTC, bobmcwhirter requested changes
LGTM

2022-05-31 15:22 UTC, dejanb commented on device/src/drivers/ble/mesh/driver/pipeline/provisioned/upper/mod.rs
> +            network_key: message.network_key.unwrap(),
Would `unwrap_or_default()` do the trick?

2022-05-31 15:30 UTC, lulf reviewed
Using option for the fields doesn't feel right. Maybe there should be a separate access message type in bluer which just uses the same opcode type and message types

2022-05-31 15:44 UTC, dejanb commented on device/src/drivers/ble/mesh/driver/pipeline/provisioned/upper/mod.rs
> +            network_key: message.network_key.unwrap(),
Yeah, actually makes sense on a second thought ... But let think about all this a bit more based on the chat conversations

2022-06-10 11:03 UTC, closed without merging

2022-06-10 11:04 UTC, dejanb commented
Closing this one as we agreed on different approach